### ISSUE TITLE
Assignment#1: Upload .gif File

### ISSUE THREAD

**Issue by ErSKS** [ErSKS/WebDesign#1]
Upload your GIF file using Photos of PM of Nepal

**Comment by ghost** [comment]
![pk gif example](https://user-images.githubusercontent.com/17109040/28014053-f2fb547a-658a-11e7-8961-9a4fc1d03fb7.gif)

**Comment by SanjeevJaiswar** [comment]
i will submit u soon sir

**Comment by bidurpanthee** [comment]
![project2](https://user-images.githubusercontent.com/30019611/28014102-24e7a146-658b-11e7-81b3-d485b33efd0f.gif)

**Comment by ErSKS** [comment]
@SanjeevJaiswar @kunwarM Submit those files #ASAP !

**Comment by pwnsbd** [comment]
![project2](https://user-images.githubusercontent.com/30019602/28014166-5ef1ce48-658b-11e7-89a1-1d7fa3e67872.gif)

**Comment by kunwarM** [comment]
![webp net-gifmaker](https://user-images.githubusercontent.com/30043711/28062002-4cef9be6-664c-11e7-9404-0762976fe092.gif)

**Comment by ErSKS** [comment]
@pwnsbd Upload your own task !
