### ISSUE TITLE
Assignment#2: Upload .psd of Basic Web Architecture

### ISSUE THREAD

**Issue by ErSKS** [ErSKS/WebDesign#2]
Upload .psd of Basic Web Architecture

**Comment by bidurpanthee** [comment]
[project33.zip](https://github.com/ErSKS/WebDesign/files/1138395/project33.zip)
![nepal](https://user-images.githubusercontent.com/30019611/28062236-fead16ce-664c-11e7-80d6-2aee4bdbb0c6.jpg)

**Comment by bidurpanthee** [comment]
![nepal](https://user-images.githubusercontent.com/30019611/28062183-d4769542-664c-11e7-932f-73f9304bee6d.jpg)

**Comment by ghost** [comment]
![3partitionexample](https://user-images.githubusercontent.com/17109040/28062301-25c0c724-664d-11e7-99e8-874ac1ca8e3f.jpg)
[3partitionexample.zip](https://github.com/ErSKS/WebDesign/files/1138396/3partitionexample.zip)
![govermental portal](https://user-images.githubusercontent.com/17109040/28062219-f4712e66-664c-11e7-8919-250cd2cf3ff4.png)

**Comment by pwnsbd** [comment]
![day3](https://user-images.githubusercontent.com/30019602/28062490-d0eae0ee-664d-11e7-99a0-b6c3569d5785.jpg)
