### ISSUE TITLE
Assignment#3: Upload .psd of Nepal Governmental Portal

### ISSUE THREAD

**Issue by ErSKS** [ErSKS/WebDesign#3]
Upload .png & .zip of .psd of Nepal Governmental Portal

**Comment by bidurpanthee** [comment]
[project3.zip](https://github.com/ErSKS/WebDesign/files/1138404/project3.zip)
![project3](https://user-images.githubusercontent.com/30019611/28062363-600c9872-664d-11e7-8c42-0db2cd50c86c.jpg)

**Comment by kunwarM** [comment]
![nepal design-recovered](https://user-images.githubusercontent.com/30043711/28101583-1028c726-66e9-11e7-8f34-6d78b2da4416.jpg)
[Nepal Design-Recovered.zip](https://github.com/ErSKS/WebDesign/files/1140866/Nepal.Design-Recovered.zip)
