### ISSUE TITLE
Design Bootstrapped Form of given design

### ISSUE THREAD

**Issue by ErSKS** [ErSKS/WebDesign#6]
![assignment - design bootstraped form](https://user-images.githubusercontent.com/5508421/28159817-efbb68ea-67dd-11e7-8a79-b25f4ebf4c3c.png)

**Comment by ghost** [comment]
![bootstrapform](https://user-images.githubusercontent.com/17109040/28178927-f115da26-681f-11e7-87eb-0360527ec939.PNG)
[bootstrapForm.zip](https://github.com/ErSKS/WebDesign/files/1146037/bootstrapForm.zip)

**Comment by ErSKS** [comment]
@prakashkarki Try to do this task in your next design [Design this as of Your College Registration Form].
